<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Content' => 'Content',
    'Entity' => 'Entity',
    'Entity ID' => 'Entity ID',
    'Parent ID' => 'Parent ID',
    'Status' => 'Status',
    'Level' => 'Level',
    'Created by' => 'Created by',
    'Updated by' => 'Related to',
    'Related to' => 'Related to',
    'Url' => 'Url',
    'Created date' => 'Created date',
    'Updated date' => 'Updated date',
    'View' => 'Ver',
    'Update' => 'Modificar',
    'Delete' => 'Eliminar',
    'Reply' => 'Responder',
    'Comments ({0})' => 'Comentarios ({0})',
    'Comment cannot be blank.' => 'El comentario no puede estar vacío.',
    'Comment has not been deleted. Please try again!' => 'El comentario no ha sido borrado. ¡Por favor, intentalo de nuevo!',
    'Add a comment...' => 'Añadir un comentario...',
    'Comment' => 'Comenta',
    'Oops, something went wrong. Please try again later.' => 'Ups, algo ha salido mal. Por favor, intentalo de nuevo más tarde.',
    'The requested page does not exist.' => 'La página solicitada no existe.',
    'Comment has been deleted.' => 'El comentario ha sido eliminado.',
    'Comment has been saved.' => 'El comentario ha sido guardado.',
    'Click here to cancel reply.' => 'Haz click aqui para cancelar la respuesta.',
    'Comments Management' => 'Gestionar comentarios',
    'Select Status' => 'Select Status',
    'Select Author' => 'Select Author',
    'Update Comment: {0}' => 'Update Comment: {0}',
    'Active' => 'Active',
    'Deleted' => 'Deleted',
    'Go Back' => 'Go Back',
];
